apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.12.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kb-lb
#spec:
#  selector:
#    app: kibana-kb-http
#  ports:
#    - protocol: TCP
#      port: 5601
#      targetPort: 5601
#  type: LoadBalancer
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: kibana-ingress
#spec:
#  defaultBackend:
#    service:
#      name: kibana
#      port:
#        number: 5601
